### ISSUE TITLE
058 - Flood Visualisation

### ISSUE THREAD

**Issue by ChevScore** [DECO3801-Group-Project/project#4]
# **Description**

## SubFeature/component (optional)
- Inundation Model
- 3-D Blender Model
- Unity/VR
- UI/UX of the Application

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.
# **Dependencies**

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- **Inundation Model (Aug. 20)**
- [ ] Inundation Model: Research and Data collection
- [ ] Inundation Model: Implementation
- [ ] Inundation Model: Refinement
- [ ] Inundation: Finalize and Integrate
- **3D Model (Blender)**
- [ ] 3D Model: Download map data
- **Unity**
- [ ] Unity: VR plug-in code
- [ ] Unity: Implementation of Mathematical Model onto the Flood Model
- [ ] Unity: Application Development
- **UI/UX**
- [ ] User testing
- [ ] Deliverables
- [ ] Presentation (Wk. 6)
- [ ] Final Submission

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.

# **Documentation**

# **Members**
- Syed Muhammad Zahir (ChevScore)
